### ISSUE TITLE
Feature request: Negative values allowed in bar graph

### ISSUE THREAD

**Issue by PifPof73** [splitbrain/dokuwiki-plugin-gchart#10]
Hi,
is it possible to display negative values in BarCharts / LineCharts?

I am using a graph to show the mean temperture of a year, and I do have a negative value in january:

`
<gchart 640x400 vbar right #9999ff #ffffff value legend "Monatsdurchschnitt 2017">
Jan = -1.57
Feb = 4.11
Mrz = 8.52
Apr = 8.64
Mai = 15.34
Jun = 19.06
Jul = 19.09
Aug = 18.10
Sep = 12.85
Okt = 11.17
Nov = 4.92
Dez = 2.63
</gchart>
`
Leads to:
![grafik](https://user-images.githubusercontent.com/7371047/35907708-ff8d26cc-0bee-11e8-921e-00487d7446c2.png)

Greetings,
PifPof73

**Comment by ntoniazzi** [comment]
Actually, this was a regression. Fixed in next version.
