### ISSUE TITLE
Deprecation of API that this plugin uses.

### ISSUE THREAD

**Issue by SMSadegh19** [splitbrain/dokuwiki-plugin-gchart#14]
I saw a deprecation notice here:
https://developers.google.com/chart/image/
and new API that Google provides is here:
https://developers.google.com/chart

and [here](https://groups.google.com/g/google-chart-api/c/rZtHTyYgyXI), they said: "Google Image Charts will be turned off soon".

I think It's better to archive this project and plugin and remove it from DokuWiki plugins list.

Or maybe someone can upgrade it to use new API of Google:
https://developers.google.com/chart/

**Comment by wschoot** [comment]
Would be great if the plugin was updated, my graphs now show 404's :)

**Comment by splitbrain** [comment]
Google's new API is JavaScript based and makes no sense for this plugin. It would work completely different. I just pushed an update that uses quickchart.io instead. Not as good looking as Google but at least charts are shown again.
