### ISSUE TITLE
Is it possible to display struct aggregation data in bar graph with this plugin?

### ISSUE THREAD

**Issue by Chris75forumname** [splitbrain/dokuwiki-plugin-gchart#15]
Is it possible to display struct aggregation data in bar graph with this plugin?
If not, it would be great to have a graph plugin compatible with struct or data plugin to show aggregated and filtered data in a bar graph!

**Comment by splitbrain** [comment]
> Is it possible to display struct aggregation data in bar graph with this plugin?

no. that's not in scope for this plugin
