### ISSUE TITLE
Make compatible with new uvCharts lib (MIT licensed)?

### ISSUE THREAD

**Issue by poVoq** [splitbrain/dokuwiki-plugin-gchart#4]
I guess this might warrant a new plugin, but since this seems to be the only actively maintained charts plugin for DokuWiki...

There is a new MIT licensed java-script library that does pretty nice charts easily, see:
https://github.com/imaginea/uvCharts

There is an implementation for Wordpress if that helps:
https://wordpress.org/plugins/easy-charts/#description

**Comment by splitbrain** [comment]
That's a completely different implementation and should be done in it's own plugin.
