### ISSUE TITLE
Since last update spaces in Text are shown as %20

### ISSUE THREAD

**Issue by PifPof73** [splitbrain/dokuwiki-plugin-gchart#6]
Hi,
we updated the plugin today and suddently all spaces in diagram textes are represented by a %20 value.

Example:
<gchart 350x120 pie3d #0000ff #ffffff left>
Apples and Bananas = 3
Peaches      = 23
Strawberries = 25
Peanuts      = 7
</gchart>

Leads to the picture attached.

![gchart_plugin](https://user-images.githubusercontent.com/7371047/35051503-ab615040-fba5-11e7-8cab-0a7eea95ff94.jpg)

**Comment by splitbrain** [comment]
@ntoniazzi sounds like it might have been introduced by your recent PR? Could you have a look?
