### ISSUE TITLE
Values are not displayed anymore

### ISSUE THREAD

**Issue by PifPof73** [splitbrain/dokuwiki-plugin-gchart#8]
Hi,
after fixing the last bug (thanks for the fast reaction), now the spaces are working, but the values are no longer displayed.
`<gchart 640x100 pie3d #0000ff #ffffff value left>
Apples and Bananas = 3
Peaches      = 23
Strawberries = 25
Peanuts      = 7
</gchart>`

leads to 

![gchart_plugin](https://user-images.githubusercontent.com/7371047/35210669-726df32c-ff53-11e7-8d83-b3f13bfb5961.jpg)

**Comment by ntoniazzi** [comment]
Fixed, sorry about this.

**Comment by splitbrain** [comment]
thanks @ntoniazzi
