### ISSUE TITLE
Spaces in title

### ISSUE THREAD

**Issue by PifPof73** [splitbrain/dokuwiki-plugin-gchart#9]
Sorry folks, I know I am bothersome.

The Spaces in the Headline are still with %20.

code:
`<gchart 640x100 pie3d #0000ff #ffffff value left "Head Line with Spaces">
Apples and Bananas = 3
Peaches      = 23
Strawberries = 25
Peanuts      = 7
</gchart>`

![gchart_plugin](https://user-images.githubusercontent.com/7371047/35263371-c7e48e2c-0018-11e8-8de2-621f2a8d56ae.jpg)

**Comment by ntoniazzi** [comment]
Fixed.
